#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
hooks:
  AfterInstall:
    - location: ~/scripts/install_images.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ~/scripts/start_server.sh
      timeout: 300
      runas: root
