#/buildspec.yml

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
      docker: 19
    commands:
      # DinD Setting
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

      ## Export Setting and Docker Login.
      - export ECR=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $ECR/

  pre_build:
    commands:
      - echo Pre_build phase..
      - npm i -g lerna
      - npm i -g eslint
      - npm run clean
      - npm run build

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_CLIENT:$IMAGE_TAG ./packages/client
      - docker build -t $IMAGE_REPO_SERVER:$IMAGE_TAG ./packages/server

      - docker tag $IMAGE_REPO_CLIENT:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_CLIENT:$IMAGE_TAG
      - docker tag $IMAGE_REPO_SERVER:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_SERVER:$IMAGE_TAG

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_CLIENT:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_SERVER:$IMAGE_TAG

  post_build:
    commands:
      - docker images
      - echo Build completed on `date`

artifacts:
  files: '**/*'
