version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Pre_build phase..
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - npm i -g lerna
      - npm i -g eslint
      - npm run clean
      - npm run build
  build:
    commands:
      - echo Build started on `date`
      - docker build -t client_test:0.3 ./packages/client
      - docker build -t server_test:0.3 ./packages/server

      - docker tag client_test:0.3 558661889689.dkr.ecr.ap-northeast-2.amazonaws.com/client_test:0.3
      - docker push 558661889689.dkr.ecr.ap-northeast-2.amazonaws.com/client_test:0.3

      - docker tag server_test:0.3 558661889689.dkr.ecr.ap-northeast-2.amazonaws.com/server_test:0.3
      - docker push 558661889689.dkr.ecr.ap-northeast-2.amazonaws.com/server_test:0.3

  post_build:
    commands:
      - docker images
      - ls -al
      - echo Build completed on `date`
artifacts:
  files:
    - 'client-0.3.tar'
    - 'server-0.3.tar'
