version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Pre_build phase..
      - npm install
      - npm i -g lerna
      - npm i -g eslint
  build:
    commands:
      - echo Build started on `date`
      - npm run clean
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
