version: 0.2

phases:
  install:
    runtime-versions:
      node: 16
  pre_build:
    commands:
      - echo Pre_build phase...
      - cd Quest-16-B/application/client
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - docker build -t client_build_test:0.3 .
      - docker save client_build_test:0.3 > client.tar
      - echo Build completed on `date`
artifacts:
  files:
    - target/notepad
